using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class Ip00Host
    {
        public string DefiMovOriginale { get; set; }
        public string DefiNumPolizza { get; set; }
        public string DefiContraente { get; set; }
        public string TestDescrizione { get; set; }
        public string De11CompCedente { get; set; }
        public string DefiNumRaggr { get; set; }
        public string CateInteresTrasp { get; set; }
        public string De11CodContraent { get; set; }
        public string DefiNumMovimento { get; set; }
        public string CateMovimentoPol { get; set; }
        public DateTime DataEmissione { get; set; }
        public DateTime DataEffettoMov { get; set; }
        public DateTime DataScadenzaMov { get; set; }
        public string RaprMovimento { get; set; }
        public decimal AnnoCompetenza { get; set; }
        public DateTime DataEffettoPol { get; set; }
        public DateTime DataScadenzaPol { get; set; }
        public decimal AnnoSottoscrizion { get; set; }
        public string CateCoassicur { get; set; }
        public decimal QutaRischioNsq { get; set; }
        public string DefiDelegataria { get; set; }
        public decimal? FrazAssicurata { get; set; }
        public string CateSettore { get; set; }
        public string CateAreaLavoro { get; set; }
        public string De11RamoTecnico { get; set; }
        public string De11CodRischio { get; set; }
        public string De11CodGaranzia { get; set; }
        public string De11DivisaEst { get; set; }
        public string De11RamoBilancio { get; set; }
        public decimal ValrAssicurato { get; set; }
        public string De11RipartoPol { get; set; }
        public string DefiCertificato { get; set; }
        public decimal ProgRata { get; set; }
        public decimal ValrPremioImpon { get; set; }
        public decimal ValrPremioNetto { get; set; }
        public decimal AnnoContabile { get; set; }
        public decimal MeseContabile { get; set; }
        public decimal BoolImportato { get; set; }
        public string CateAccount { get; set; }
        public decimal ValrTasseLocali { get; set; }
        public string CateTipoPolizza { get; set; }
        public string De11PaeseRischio { get; set; }
        public string De11OperazContab { get; set; }
        public DateTime? DataBilancio { get; set; }
        public string DefiNumPolBase { get; set; }
        public string De20Param1 { get; set; }
        public string De20Param2 { get; set; }
        public string De20Param3 { get; set; }
        public string De20Param4 { get; set; }
        public string De20Param5 { get; set; }
        public string De20Param6 { get; set; }
        public string De20Param7 { get; set; }
        public string De20Param8 { get; set; }
        public string De20Param9 { get; set; }
        public string De20Param10 { get; set; }
        public string De20Param11 { get; set; }
        public string De20Param12 { get; set; }
        public string De20Param13 { get; set; }
        public string De20Param14 { get; set; }
        public string De20Param15 { get; set; }
        public string De20Param16 { get; set; }
        public string De20Param17 { get; set; }
        public string De20Param18 { get; set; }
        public string De20Param19 { get; set; }
        public string De20Param20 { get; set; }
        public string De16CodAgenzia { get; set; }
        public string De20CodProdotto { get; set; }
        public decimal ValrMur { get; set; }
        public decimal ValrMpl { get; set; }
        public string CateComponentMov { get; set; }
        public string CateRischioCauzioni { get; set; }
        public string De20CodCliente { get; set; }
        public DateTime? DataNascitaCli { get; set; }
        public string CateSesso { get; set; }
        public string CateFinanziamento { get; set; }
        public DateTime? DataScadenzaRata { get; set; }
        public decimal ValrCapitalFinan { get; set; }
        public decimal FrazFinanziario { get; set; }
        public decimal FrazPremio { get; set; }
        public string CateRataFinanzia { get; set; }
        public DateTime? DataEstinzione { get; set; }
        public string DefiCognomeAssic { get; set; }
        public string DefiCodiceFiscal { get; set; }
        public decimal? NumrEtaScadePol { get; set; }
        public decimal? NumrEtaEffetPol { get; set; }
        public DateTime? DataAdesione { get; set; }
        public string CatePeriodPremio { get; set; }
        public decimal FrazCalcoloPremi { get; set; }
        public decimal NumrTesteAssic { get; set; }
        public decimal NumrPeriodPremio { get; set; }
        public string De20CodGestore { get; set; }
        public decimal BoolClaims { get; set; }
        public decimal NumrDurataClaims { get; set; }
        public decimal BoolPostuma { get; set; }
        public decimal NumrDurataPostum { get; set; }
        public string De20Lob { get; set; }
        public string De20Gor { get; set; }
        public string De20Cat { get; set; }
        public decimal ValrCommissioniDir { get; set; }
        public string DefiIdenOriginale { get; set; }
        public string CateRateoPrRisc { get; set; }
    }
}
