using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class PrGarTariffe
    {
        public decimal KeyPrGarTariffa { get; set; }
        public decimal? IdPrGarTariffa { get; set; }
        public decimal? IdUtente { get; set; }
        public string CodTariffa { get; set; }
        public decimal? IdDescTariffa { get; set; }
        public decimal? IdFormula { get; set; }
        public string Note { get; set; }
        public decimal? DivisoreBaseCalcolo { get; set; }
        public string FlgTipoPremio { get; set; }
        public string FlgTassoObbSino { get; set; }
        public string FlgTassoDirettoSino { get; set; }
        public string FlgGruppoObbSino { get; set; }
        public string FlgBeneficiarioMorteSino { get; set; }
        public string FlgBeneficiarioVitaSino { get; set; }
        public string FlgBeneficiarioAltroSino { get; set; }
        public string FlgRegolaAnaBenefAltro { get; set; }
        public string FlgForzaCapitaleSino { get; set; }
        public string FlgRicCapitale1Sino { get; set; }
        public string FlgRicCapitale2Sino { get; set; }
        public string FlgRicAddettiSino { get; set; }
        public string FlgRicMaxSinSino { get; set; }
        public string FlgRicMaxPersSino { get; set; }
        public string FlgRicMaxCoseSino { get; set; }
        public string FlgRicMaxIntSino { get; set; }
        public string FlgRicTassoSino { get; set; }
        public string FlgRicPremioSino { get; set; }
        public string FlgRicFrancSino { get; set; }
        public string FlgRicPctScopSino { get; set; }
        public string FlgRicMaxScopSino { get; set; }
        public string FlgLabelCapitale1 { get; set; }
        public string FlgLabelCapitale2 { get; set; }
        public string FlgLabelAddetti { get; set; }
        public string FlgVarCapitale1Sino { get; set; }
        public string FlgVarCapitale2Sino { get; set; }
        public string FlgVarAddettiSino { get; set; }
        public string FlgVarMaxSinSino { get; set; }
        public string FlgVarMaxPersSino { get; set; }
        public string FlgVarMaxCoseSino { get; set; }
        public string FlgVarMaxIntSino { get; set; }
        public string FlgVarTassoSino { get; set; }
        public string FlgVarPremioSino { get; set; }
        public string FlgVarFrancSino { get; set; }
        public string FlgVarPctScopSino { get; set; }
        public string FlgVarMaxScopSino { get; set; }
        public string FlgVisCapitale1Sino { get; set; }
        public string FlgVisCapitale2Sino { get; set; }
        public string FlgVisAddettiSino { get; set; }
        public string FlgVisMaxSinSino { get; set; }
        public string FlgVisMaxPersSino { get; set; }
        public string FlgVisMaxCoseSino { get; set; }
        public string FlgVisMaxIntSino { get; set; }
        public string FlgVisTassoSino { get; set; }
        public string FlgVisPremioSino { get; set; }
        public string FlgVisFrancSino { get; set; }
        public string FlgVisPctScopSino { get; set; }
        public string FlgVisMaxScopSino { get; set; }
        public string FlgRamoBilancio { get; set; }
        public string FlgCatTariffa { get; set; }
        public decimal? IdTasse { get; set; }
        public decimal? IdSsn { get; set; }
        public decimal? IdFvs { get; set; }
        public decimal? IdAntiracket { get; set; }
        public string FlgGaranziaRcaSino { get; set; }
        public string FlgTuttiSettoriSino { get; set; }
        public decimal? IdPrGarTariffaCollegata { get; set; }
        public decimal? PctTariffaCollegata { get; set; }
        public string FlgTipoSinistro { get; set; }
        public string FlgLineaProdotto { get; set; }
        public DateTime? DtStoEffettoLog { get; set; }
        public DateTime? DtStoScadenzaLog { get; set; }
        public string DtStoEffettoFis { get; set; }
        public string DtStoScadenzaFis { get; set; }
        public string DescTariffa { get; set; }
        public string FlgTassoLordoSino { get; set; }
        public string FlgNonSoggIntFrazSino { get; set; }
        public string FlgTipoTariffa { get; set; }
        public string FlgCodTassaProvinciale { get; set; }
        public string FlgTipoCapitale { get; set; }
        public decimal? TassoSmontCapitale { get; set; }
        public string FlgTipoFrazAntidurate { get; set; }
        public string FlgRicScadGaranziaSino { get; set; }
        public int? IdFormulaScadenza { get; set; }
        public string FlgTipoValScadenza { get; set; }
        public int? IdFormulaCapitale { get; set; }
        public string FlgPresenzaGruppiTerSino { get; set; }
        public string FlgClRischioObbSino { get; set; }
        public string FlgClassiRischioVeicSino { get; set; }
        public string FlgCapitale1SezioneSino { get; set; }
        public string FlgAddettiSezioneSino { get; set; }
        public string FlgPremioZeroSino { get; set; }
        public int? IdPrEvoluzioneBm { get; set; }
        public string FlgFranchigiaAggSino { get; set; }
        public decimal? ImpFranchigiaAgg { get; set; }
        public string FlgTipoFranchigiaAgg { get; set; }
        public decimal? PctFranchigiaAggregata { get; set; }
        public string FlgRicGrTerContraSino { get; set; }
        public string FlgRamoTecnico { get; set; }
        public string FlgTipoSchedaDanno { get; set; }
        public string FlgAzzeraRateSuccSino { get; set; }
        public string FlgInclPremioFissoSino { get; set; }
        public string FlgPresenzaSexEtaSino { get; set; }
        public string CodInterno { get; set; }
    }
}
