using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class PrProdotti
    {
        public decimal KeyPrProdotto { get; set; }
        public decimal IdPrProdotto { get; set; }
        public decimal? IdPrRamo { get; set; }
        public decimal? IdUtente { get; set; }
        public string CodProdotto { get; set; }
        public decimal? IdDescProdotto { get; set; }
        public string Note { get; set; }
        public string FlgTacRinnovoSino { get; set; }
        public decimal? AaMaxDurata { get; set; }
        public string FlgTipoCalendario { get; set; }
        public string FlgIndiceCompSino { get; set; }
        public string FlgObbCompSino { get; set; }
        public string FlgIndiceIstatSino { get; set; }
        public string FlgObbIstatSino { get; set; }
        public string FlgTipoAccessori { get; set; }
        public string FlgTaglioFissoSino { get; set; }
        public decimal? PctMinAccessori { get; set; }
        public decimal? PctMaxAccessori { get; set; }
        public decimal? ImpPremioMin { get; set; }
        public string FlgModProv { get; set; }
        public string FlgModProvPoli { get; set; }
        public string FlgRetiAbilSino { get; set; }
        public string FlgPuntiAbilSino { get; set; }
        public string FlgEsclusivaSino { get; set; }
        public string FlgNsDelegaSino { get; set; }
        public string FlgAltruiDelegaSino { get; set; }
        public string FlgStatoProdotto { get; set; }
        public decimal? NGgEmisPostergata { get; set; }
        public decimal? NGgEmisAntergata { get; set; }
        public decimal? NGgDurataProposta { get; set; }
        public string FlgTipoRegolazione { get; set; }
        public string FlgRamoBilancio { get; set; }
        public string FlgCatTariffa { get; set; }
        public decimal? IdTasse { get; set; }
        public decimal? IdSsn { get; set; }
        public decimal? IdFvs { get; set; }
        public decimal? IdAntiracket { get; set; }
        public decimal? AaMinDurata { get; set; }
        public string FlgCumuloCapitaleSino { get; set; }
        public string FlgTipoArrotondamento { get; set; }
        public decimal? ImpArrotondamento { get; set; }
        public string FlgProntaEmissioneSino { get; set; }
        public string FlgPeriodoPerfezionamento { get; set; }
        public decimal? GgPerfezionamento { get; set; }
        public decimal? ImpCapitaleMinResiduo { get; set; }
        public string FlgTacRinnovoObbSino { get; set; }
        public string FlgCollettiveFlottaSino { get; set; }
        public string FlgStesseGaranzieSino { get; set; }
        public string FlgStessiValoriSino { get; set; }
        public decimal? IdIstat { get; set; }
        public string FlgTipoAllegati { get; set; }
        public string FlgDigitaPolizzaSino { get; set; }
        public string FlgDigitaPropostaSino { get; set; }
        public string FlgMultivalutaSino { get; set; }
        public string FlgTrattazioneSino { get; set; }
        public DateTime? DtStoEffettoLog { get; set; }
        public DateTime? DtStoScadenzaLog { get; set; }
        public string DtStoEffettoFis { get; set; }
        public string DtStoScadenzaFis { get; set; }
        public string FlgSinistroSuPropostaSino { get; set; }
        public string FlgDerogaPolizzaSino { get; set; }
        public string DescProdotto { get; set; }
        public string FlgStampaPolIncasSino { get; set; }
        public string FlgIncassoFuoriSeqSino { get; set; }
        public string FlgTuttiProdCollegatiSino { get; set; }
        public string FlgCollContrSino { get; set; }
        public string FlgExtraCompSino { get; set; }
        public decimal? ImpDirAnnullamento { get; set; }
        public string FlgDirAnnSoggProvvSino { get; set; }
        public string FlgRichNPropostaSino { get; set; }
        public string FlgCodTassaProvinciale { get; set; }
        public string FlgPolizzaDaPreventivoSino { get; set; }
        public decimal? ImpPremioMinLordo { get; set; }
        public string FlgDerogaPremioMinLordo { get; set; }
        public int? LimiteGgRateoPrimaRata { get; set; }
        public string FlgProdottoApertoSino { get; set; }
        public decimal? CodDerogaPolizza { get; set; }
        public string FlgDerogaNsDelegaSino { get; set; }
        public decimal? CodDerogaNsDelega { get; set; }
        public string FlgDerogaAltruiDelegaSino { get; set; }
        public decimal? CodDerogaAltruiDelega { get; set; }
        public string FlgDerogaAccessoriSino { get; set; }
        public decimal? CodDerogaAccessori { get; set; }
        public string FlgDerogaPremioMinSino { get; set; }
        public decimal? CodDerogaPremioMin { get; set; }
        public string FlgDerogaRiservatoSino { get; set; }
        public decimal? CodDerogaRiservato { get; set; }
        public string FlgDerogaAllegatiSino { get; set; }
        public decimal? CodDerogaAllegati { get; set; }
        public int? CodDerogaPremioMinLordo { get; set; }
        public int? GgLimiteInclusione { get; set; }
        public decimal? PctDefaultAccessori { get; set; }
        public string FlgQzInfrFissoSino { get; set; }
        public string FlgRimbRegPremioSino { get; set; }
        public int? NumGgMora { get; set; }
        public decimal? ImpAccessoriMin { get; set; }
        public decimal? ImpAccessoriMax { get; set; }
        public decimal? ImpAccessoriDefault { get; set; }
        public string FlgDerogaAnterPosterSino { get; set; }
        public decimal? CodDerogaAnterPoster { get; set; }
        public int? NumGgMinDurTemporanea { get; set; }
        public int? NumGgMaxDurTemporanea { get; set; }
        public int? GgMaxPosterTrasfProp { get; set; }
        public string FlgFranchigiaAggSino { get; set; }
        public int? PctLimiteInclusione { get; set; }
        public string FlgTpAbilPrPreventivo { get; set; }
        public DateTime? DtTermineEmissione { get; set; }
        public DateTime? DtTermineRinnovo { get; set; }
        public string FlgAbilLimRateoSostSino { get; set; }
        public string FlgCoobbligatoSino { get; set; }
        public string BloccoQzNoTacRinnSino { get; set; }
        public string FlgAbilScadPolCrusSino { get; set; }
        public string FlgPropostaRinnovoSino { get; set; }
        public string FlgAbilModQuietSino { get; set; }
        public string FlgTipoAbbScRca { get; set; }
        public string FlgRateizzazionePremioSino { get; set; }
        public string FlgDisabilTerritSino { get; set; }
        public string FlgTuttiTargetMarketSino { get; set; }
        public string FlgTemplateWise { get; set; }
        public string FlgDerogaTerritSino { get; set; }
        public int? CodDerogaTerrit { get; set; }
        public string FlgInstantInsuranceSino { get; set; }
        public string FlgDataAccEventoSino { get; set; }
        public string FlgTipologiaDocumentale { get; set; }
        public string FlgTacRinnovoDefaultSino { get; set; }
        public string TooltipInfo { get; set; }
        public string FlgDerogaPosterSino { get; set; }
        public decimal? CodDerogaPoster { get; set; }
        public string FlgCodfisAssFacSino { get; set; }
    }
}
